### ISSUE TITLE
Request: compile using nuitka

### ISSUE THREAD

**Issue by katakombi** [blueOkiris/bgrm#12]
In the past Ive had great success in compiling binaries from python scripts using nuitka.
This would be great as it will help to get rid of any python dependencies.

**Comment by katakombi** [comment]
I've tried to give it a go but apparently it couldn't find opencv. I think it may have to do that the nuitka version is defaulting to python 3.8 and this is where it fails to find the 3.9 version of opencv. 

Ive messed up my python installation over this, so I may return with a more usable compilation output as soon as I am done restoring it.

**Comment by blueOkiris** [comment]
I may have actually been wrong about it needing Python 3.9. Very recently, I looked into the features that I thought weren't in previous versions and they may work from with 3.8. Obviously, I'm not certain

**Comment by blueOkiris** [comment]
Closing bc old
