### ISSUE TITLE
On wayland: could not connect to display

### ISSUE THREAD

**Issue by zauster** [blueOkiris/bgrm#15]
Hey,

very nice project!

I was able to bring it to run on xorg (on another laptop), but not on wayland. I am seeing this error:

```
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
qt.qpa.xcb: could not connect to display :1.0
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "/path/build/sources/bgrm/.venv/lib/python3.9/site-packages/cv2/qt/plugins" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: xcb.
```

I tried setting DISPLAY to other values (e.g. WAYLAND_DISPAY). Could these envvars be relevant?

```
QT_QPA_PLATFORM=wayland
QT_WAYLAND_DISABLE_WINDOWDECORATION=1
```

Is it even supposed to run on wayland?

**Comment by blueOkiris** [comment]
With the latest Flatpak version I've created, I have been able to launch with Wayland (without setting any variables).
Feel free to comment if you decide to give it another go and run into the same issue, but I'm closing this since it does work on Wayland in at least one context.
