### ISSUE TITLE
low fps when using

### ISSUE THREAD

**Issue by agent255** [blueOkiris/bgrm#16]
i get ~6 fps with bgrm and 30 without, my specs are :
❯ neofetch

 OS: Gentoo/Linux x86_64
     Host: ROG Strix GL10CS 1.0
    Kernel: 5.10.61-gentoo-x86_64
   Uptime: 58 mins
 Packages: 1106 (emerge)
 Shell: zsh 5.8
    Resolution: 1920x1080
  WM: i3
  Theme: Adwaita [GTK2/3]
     Icons: Adwaita [GTK2/3]
      Terminal: st
         Terminal Font: JoyPixels
            CPU: Intel i7-9700K (8) @ 4.900GHz
             GPU: NVIDIA GeForce GTX 1660 Ti
                 Memory: 1055MiB / 7880MiB

**Comment by blueOkiris** [comment]
Closing since it's been a month with no reply on whether that worked.
