### ISSUE TITLE
Inappropriate ioctl for device error

### ISSUE THREAD

**Issue by zeirew** [blueOkiris/bgrm#17]
Hi, I'm having trouble actually getting this set up. I get this error when I try to run the bgrm script:

> INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
> Traceback (most recent call last):
>   File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
>     return _run_code(code, main_globals, None,
>   File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
>     exec(code, run_globals)
>   File "/home/Desktop/Misc./Software/bgrm/bgrm/__main__.py", line 4, in <module>
>     main()
>   File "/home/Desktop/Misc./Software/bgrm/bgrm/bgrm.py", line 28, in main
>     formatVirtualCamera(settings, virtCam, cam)
>   File "/home/Desktop/Misc./Software/bgrm/bgrm/bgrm.py", line 66, in formatVirtualCamera
>     ioctl(virtCam, VIDIOC_S_FMT, format)
> OSError: [Errno 25] Inappropriate ioctl for device

A few weeks ago, I was able to get this running after testing out some other solutions, like linux-fake-webcam; however, it would work on zoom, but not teams, which was my target application. Now I'm not getting it to work at all. Any help would be much appreciated.

**Comment by blueOkiris** [comment]
Have you tried changing the camera?
Do `ls /dev/ | grep -i video` and see if you have anything other than /dev/video0 and /dev/video1.

If so, try running it with `-c ##` where ## corresponds to /dev/video##

**Comment by blueOkiris** [comment]
It's likely the same [as this issue](https://github.com/blueOkiris/bgrm/issues/2), which remains unsolved unfortunately

**Comment by ze1nab** [comment]
> Have you tried changing the camera? Do `ls /dev/ | grep -i video` and see if you have anything other than /dev/video0 and /dev/video1.
> 
> If so, try running it with `-c ##` where ## corresponds to /dev/video##

I currently only have one camera, so not yet. Here's what I get when for the contents of /dev/video*:

```
crw-rw----+ 1 root video 81, 0 Dec  9 20:35 /dev/video0
crw-rw----+ 1 root video 81, 1 Dec  9 20:35 /dev/video1
-rw-r--r--  1 root root      0 Dec  9 20:52 /dev/video10
```
And when I try to run with -c 1 or -c 10, I get this error:
```
[ WARN:0] global /tmp/pip-req-build-v1rk7obu/opencv/modules/videoio/src/cap_v4l.cpp (893) open VIDEOIO(V4L2:/dev/video10): can't open camera by index
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/Desktop/Misc./Software/bgrm/bgrm/__main__.py", line 4, in <module>
    main()
  File "/home/Desktop/Misc./Software/bgrm/bgrm/bgrm.py", line 27, in main
    with Cam(settings) as cam, open('/dev/video10', 'wb') as virtCam:
  File "/home/Desktop/Misc./Software/bgrm/bgrm/cam.py", line 22, in __init__
    _height, _width, self.channels = baseFrame.shape
AttributeError: 'NoneType' object has no attribute 'shape'
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.


```

**Comment by ze1nab** [comment]
> It's likely the same [as this issue](https://github.com/blueOkiris/bgrm/issues/2), which remains unsolved unfortunately

Yeah, I guess I'm even getting the same secondary error as they are.

**Comment by blueOkiris** [comment]
What is your kernel? Do `uname -a`

**Comment by blueOkiris** [comment]
I realize it's been a while, but I may have found a solution in the aforementioned issue after running into the same issue myself after switching to GNOME and Fedora

**Comment by blueOkiris** [comment]
Closing bc old
