### ISSUE TITLE
Current numpy/selected opencv won't install

### ISSUE THREAD

**Issue by blueOkiris** [blueOkiris/bgrm#19]
Having issues currently with python 3.10 and installing the required packages via pip in the virtualenv.

Currently working on a fix

**Comment by blueOkiris** [comment]
Just did a fix that should have resolved the issue.

**Comment by blueOkiris** [comment]
Yep it worked. Closing

**Comment by blueOkiris** [comment]
It'll be a while before I can update the DEBIAN package

**Comment by isopix** [comment]
Thanks, it's still very ugly packaged that it calls 'pip' (last time it hanged, holding pacman), etc.

Requires and BuildRequires should be enough to satisfy dependencies IMHO.
And why run python3.9 or python 3.10 and not 'python' or 'python3'? (I'm not programmer, so no python or python packaging knowledge, but I hadn't similar problems with other packages like this.

cheers and happy new years.
