### ISSUE TITLE
Python 3.11 Support

### ISSUE THREAD

**Issue by blueOkiris** [blueOkiris/bgrm#24]
Waiting on [mediapipe](https://pypi.org/project/mediapipe/) to have a 3.11 version

**Comment by hardpenguin** [comment]
I believe it does now :) The installation of bgrm fails on it though because there is a fixed version dependency on mediapipe.

**Comment by blueOkiris** [comment]
I'll look into it and update it when I get a chance

**Comment by blueOkiris** [comment]
Success!
