### ISSUE TITLE
Operands could not be brodcasted together

### ISSUE THREAD

**Issue by raffaelemancuso** [blueOkiris/bgrm#26]
```
❯ python -m bgrm --camera 3 --bg webcam_background.jpg  
qt.qpa.plugin: Could not find the Qt platform plugin "wayland" in "$HOME/.pyvenv/bgrm/lib/python3.11/site-packages/cv2/qt/plugins"
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
Format loopback format result (0 good): 0
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "$HOME/.pyvenv/bgrm/lib/python3.11/site-packages/bgrm/__main__.py", line 4, in <module>
    main()
  File "$HOME/.pyvenv/bgrm/lib/python3.11/site-packages/bgrm/bgrm.py", line 20, in main
    _frame, no_bg_frame, stacked_frames = cam.frames()
                                          ^^^^^^^^^^^^
  File "$HOME/.pyvenv/bgrm/lib/python3.11/site-packages/bgrm/cam.py", line 61, in frames
    no_bg_frame = self._segmentor.removeBG(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "$HOME/.pyvenv/bgrm/lib/python3.11/site-packages/cvzone/SelfiSegmentationModule.py", line 34, in removeBG
    imgOut = np.where(condition, img, imgBg)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: operands could not be broadcast together with shapes (720,1280,3) (720,1280,3) (960,1280,3) 
```

**Comment by blueOkiris** [comment]
Looks like tensorflow doesn't work on Wayland or something or you might be missing the `qtwayland` system package as well

**Comment by blueOkiris** [comment]
I think you need to add `-H 720`

The default aspect ratio is 4:3 (1280x960) but your camera gives 1280x720 which is 16:9

**Comment by raffaelemancuso** [comment]
> I think you need to add `-H 720`
> 
> The default aspect ratio is 4:3 (1280x960) but your camera gives 1280x720 which is 16:9

Thank you.

With `-H 720` it works.

But I don't like the result (some part of the background still visible).

And how can I close the "feed" window? it keeps reopening everytime I close it

**Comment by blueOkiris** [comment]
> some part of the background still visible

Sounds like you need to adjust some parameters from the defaults. You can see all the options via `-h` Most relevant is probably `-T`, the threshold for what counts as background.

> And how can I close the "feed" window? it keeps reopening everytime I close it

You can't close it (the close and reopen is just how OpenCV windows work), but you can tell it not to open in the first place via the `--disable_window` cli argument

**Comment by raffaelemancuso** [comment]
> Sounds like you need to adjust some parameters from the defaults. You can see all the options via `-h` Most relevant is probably `-T`, the threshold for what counts as background.

Thank you.

The default value seems to be 0.4. 

The range seems to be from 0 to 1.

The higher it is, the more things are removed.

**Comment by raffaelemancuso** [comment]
THanks
